name: credit_story_player_example
description: Demo app for credit_story_player.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  credit_story_player:
    path: ../
  http: ^1.2.0
  just_audio: ^0.9.40

flutter:
  uses-material-design: true
